version: "3"

services:
  ###################################################################
  # -------------------------- frontend --------------------------- #
  ###################################################################
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  ###################################################################
  # -------------------------- backend ---------------------------- #
  ###################################################################
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    env_file:
      - backend/backend.env
